app:
  name: estore-product-kube-webhook
  freeze:
    startTime: 2020-01-01T21:22:18-08:00
    endTime: 2020-01-02T21:22:18-08:00
    message: application not available at this point of time to use due to code release
    components: all
  log:
    level: debug
cluster:
  name: minikube
